import type { Coupon, DiscountItem } from "./types";

export type { DiscountItem };

export const coupons: Coupon[] = [
  {
    id: 1,
    name: "메이플스토리",
    description: "Nexon",
    image: "https://edge.ssalmuk.com/editorImage/1da2fd817f7d4a89be566fbed7df3bf9.jpg",
    bannerImages: [
      "https://play-lh.googleusercontent.com/v972nBr0WsG3HaYJo-i15UembahYSMwlSzS-OGr8bEeRHR_fYraWUWO6okYA9izUroHtdB0OTN2ZZHCsG32z1Kc=w526-h296-rw",
      "https://play-lh.googleusercontent.com/li8xilWmbq-JMNjSckRNtdj4Pc5FsxBHRNpy0LH1YB7F5h2ALrUSHLQa_wYSTZsv12g=w526-h296-rw",
    ],
    genre: "MMORPG",
    codes: [
      {
        code: "U323KSK3K1K23K",
        issueDate: "2025-10-30",
        expireDate: "정보없음",
        event: "물약100개, 초보자 방어구 세트",
        author: "쿠폰다내꺼",
      },
      {
        code: "U323KSK3K1K23K",
        issueDate: "2025-09-16",
        expireDate: "정보없음",
        event: "물약100개, 초보자 방어구 세트",
      },
    ],
    discountItems: [
      { id: 1, name: "메소 × 5000만", description: "메소 직접 충전", type: "UID", discount: 15, originalPrice: 29000 },
      { id: 2, name: "메소 × 1억", description: "메소 대량 직접 충전", type: "UID", discount: 18, originalPrice: 55000 },
      { id: 3, name: "아케인심볼 패키지", description: "아케인심볼 성장 지원 패키지", type: "PIN", discount: 10, originalPrice: 49000 },
      { id: 4, name: "어센틱심볼 패키지", description: "어센틱심볼 고급 성장 패키지", type: "PIN", discount: 12, originalPrice: 69000 },
      { id: 5, name: "넥슨캐시 × 10만", description: "넥슨캐시 직접 충전", type: "UID", discount: 10, originalPrice: 100000 },
      { id: 6, name: "스타포스 강화팩", description: "스타포스 강화 지원 + 파괴방지 쿠폰", type: "PIN", discount: 20, originalPrice: 39000 },
      { id: 7, name: "보스 입장권 패키지", description: "주요 보스 추가 입장권 번들", type: "PIN", discount: 15, originalPrice: 19000 },
      { id: 8, name: "펫 3종 패키지", description: "펫 + 장비 + 먹이 번들", type: "PIN", discount: 13, originalPrice: 89000 },
    ],
  },
  {
    id: 2,
    name: "아이온2",
    description: "NCSOFT",
    image: "https://edge.ssalmuk.com/editorImage/daa326b1f7d141dbb6f42473312e562c.jfif",
    bannerImages: [
      "https://play-lh.googleusercontent.com/li8xilWmbq-JMNjSckRNtdj4Pc5FsxBHRNpy0LH1YB7F5h2ALrUSHLQa_wYSTZsv12g=w526-h296-rw",
      "https://play-lh.googleusercontent.com/v972nBr0WsG3HaYJo-i15UembahYSMwlSzS-OGr8bEeRHR_fYraWUWO6okYA9izUroHtdB0OTN2ZZHCsG32z1Kc=w526-h296-rw",
    ],
    genre: "MMORPG",
    codes: [
      {
        code: "AION2LAUNCH",
        issueDate: "2025-08-01",
        expireDate: "2025-12-31",
        event: "출시 기념 쿠폰",
      },
    ],
    discountItems: [
      { id: 1, name: "아이온 코인 × 2000", description: "아이온 코인 소량 충전", type: "UID", discount: 10, originalPrice: 22000 },
      { id: 2, name: "아이온 코인 × 5000", description: "아이온 코인 직접 충전", type: "UID", discount: 12, originalPrice: 55000 },
      { id: 3, name: "아이온 코인 × 10000", description: "아이온 코인 대량 충전", type: "UID", discount: 15, originalPrice: 99000 },
      { id: 4, name: "아이온 코인 × 20000", description: "아이온 코인 최대량 충전", type: "UID", discount: 18, originalPrice: 185000 },
      { id: 5, name: "아이온 코인 × 50000", description: "아이온 코인 프리미엄 충전", type: "UID", discount: 20, originalPrice: 440000 },
      { id: 6, name: "아이온 코인 × 100000", description: "아이온 코인 최고 등급 충전", type: "UID", discount: 22, originalPrice: 860000 },
    ],
  },
  {
    id: 3,
    name: "RF 온라인 넥스트",
    description: "Webzen",
    image: "https://edge.ssalmuk.com/editorImage/6f0ee3a64cd14ca293dd200cfdbdd918.jpg",
    genre: "MMORPG",
    codes: [
      {
        code: "RFNEXT2025",
        issueDate: "2025-06-01",
        expireDate: "정보없음",
        event: "사전예약 쿠폰",
      },
    ],
    discountItems: [
      { id: 1, name: "RF 캐시 × 10000", description: "게임 캐시 직접 충전", type: "UID", discount: 18, originalPrice: 110000 },
      { id: 2, name: "RF 캐시 × 5000", description: "게임 캐시 충전", type: "UID", discount: 15, originalPrice: 59000 },
      { id: 3, name: "전투원 패키지", description: "장비 강화 + 소모품 번들", type: "PIN", discount: 15, originalPrice: 39000 },
      { id: 4, name: "종족 한정 무기팩", description: "종족별 전용 한정 무기 세트", type: "PIN", discount: 20, originalPrice: 79000 },
      { id: 5, name: "광산 채굴 패키지", description: "채굴 도구 + 부스터 번들", type: "PIN", discount: 12, originalPrice: 29000 },
      { id: 6, name: "부활 스크롤 패키지", description: "부활 스크롤 대량 번들", type: "PIN", discount: 10, originalPrice: 19000 },
      { id: 7, name: "길드 지원팩", description: "길드 버프 아이템 + 코인 번들", type: "PIN", discount: 17, originalPrice: 45000 },
      { id: 8, name: "시즌 패스 프리미엄", description: "시즌 배틀패스 프리미엄 등급", type: "PIN", discount: 13, originalPrice: 35000 },
    ],
  },
  {
    id: 4,
    name: "70억 좀비 히어로",
    description: "HAEGIN",
    image: "https://edge.ssalmuk.com/editorImage/d2008bde9fe541edabc5762d18b04e7b.png",
    genre: "RPG",
    codes: [
      {
        code: "ZOMBIE7B",
        issueDate: "2025-07-15",
        expireDate: "2025-11-30",
        event: "시즌 오픈 쿠폰",
      },
    ],
    discountItems: [
      { id: 1, name: "히어로 소환권 5장", description: "S급 히어로 소환권 번들", type: "PIN", discount: 12, originalPrice: 25000 },
      { id: 2, name: "히어로 소환권 10장", description: "S급 히어로 소환권 번들", type: "PIN", discount: 15, originalPrice: 49000 },
      { id: 3, name: "히어로 소환권 30장", description: "S급 히어로 10연속 소환 3세트", type: "PIN", discount: 18, originalPrice: 139000 },
      { id: 4, name: "생존자 장비팩", description: "최고급 방어구 + 무기 번들", type: "PIN", discount: 18, originalPrice: 39000 },
      { id: 5, name: "경험치 부스터팩", description: "7일 경험치 200% 부스터", type: "PIN", discount: 10, originalPrice: 19000 },
      { id: 6, name: "시즌 패스", description: "이번 시즌 배틀패스 전체", type: "PIN", discount: 12, originalPrice: 29000 },
      { id: 7, name: "좀비 킬러 세트", description: "한정 무기 스킨 + 효과 번들", type: "PIN", discount: 20, originalPrice: 59000 },
    ],
  },
  {
    id: 5,
    name: "99강화 나무 몽둥이 키우기",
    description: "SuperPlanet",
    image: "https://edge.ssalmuk.com/editorImage/8daa1b53fba545ffb56d1cac5517407b.png",
    genre: "방치형",
    codes: [
      {
        code: "WOODSTICK2025",
        issueDate: "2025-08-01",
        expireDate: "2025-12-31",
        event: "출시 기념 쿠폰",
      },
    ],
  },
  {
    id: 6,
    name: "리니지M",
    description: "NCSOFT",
    image: "https://edge.ssalmuk.com/editorImage/f85655d36efc44aaaf692cbef435271d.jpg",
    genre: "MMORPG",
    codes: [
      {
        code: "LINAGEMVIP",
        issueDate: "2025-09-01",
        expireDate: "2025-12-31",
        event: "복귀 유저 지원 패키지",
      },
    ],
    discountItems: [
      { id: 1, name: "다이아 × 8000", description: "다이아 직접 충전", type: "UID", discount: 12, originalPrice: 99000 },
      { id: 2, name: "다이아 × 3000", description: "다이아 소량 충전", type: "UID", discount: 10, originalPrice: 39000 },
      { id: 3, name: "혈맹 강화 패키지", description: "혈맹 아이템 + 다이아 번들", type: "PIN", discount: 10, originalPrice: 59000 },
      { id: 4, name: "복귀자 지원팩", description: "복귀 유저 전용 혜택", type: "PIN", discount: 15, originalPrice: 19000 },
      { id: 5, name: "전설 무기 소환팩", description: "전설등급 무기 소환권 5장", type: "PIN", discount: 18, originalPrice: 69000 },
      { id: 6, name: "아인하사드 축복", description: "7일 아인하사드 축복 아이템", type: "PIN", discount: 13, originalPrice: 35000 },
      { id: 7, name: "강화 주문서 팩", description: "안전 강화 주문서 대량 번들", type: "PIN", discount: 20, originalPrice: 45000 },
    ],
  },
  {
    id: 7,
    name: "오딘: 발할라 라이징",
    description: "Kakao Games",
    image: "https://edge.ssalmuk.com/editorImage/56ce60fa47784514b73aa0afafbecc99.jpg",
    genre: "MMORPG",
    codes: [
      {
        code: "ODIN2025NEW",
        issueDate: "2025-07-01",
        expireDate: "2025-10-31",
        event: "신규 클래스 출시 기념 쿠폰",
      },
    ],
    discountItems: [
      { id: 1, name: "오딘 크리스탈 × 6000", description: "크리스탈 직접 충전", type: "UID", discount: 20, originalPrice: 79000 },
      { id: 2, name: "오딘 크리스탈 × 12000", description: "크리스탈 대량 충전", type: "UID", discount: 22, originalPrice: 149000 },
      { id: 3, name: "발할라 패스", description: "시즌 배틀패스", type: "PIN", discount: 10, originalPrice: 14900 },
      { id: 4, name: "발할라 패스 프리미엄", description: "시즌 배틀패스 프리미엄 등급", type: "PIN", discount: 15, originalPrice: 29000 },
      { id: 5, name: "신규 클래스 스타터팩", description: "신규 클래스 전용 장비 + 스킬 번들", type: "PIN", discount: 18, originalPrice: 59000 },
      { id: 6, name: "룬 강화팩", description: "룬 강화 재료 + 보호 주문서 번들", type: "PIN", discount: 13, originalPrice: 39000 },
      { id: 7, name: "발키리 외형 세트", description: "한정 발키리 코스튬 + 무기 외형", type: "PIN", discount: 25, originalPrice: 89000 },
      { id: 8, name: "토르 축복 패키지", description: "경험치 부스터 + 드롭 증가 7일", type: "PIN", discount: 12, originalPrice: 25000 },
    ],
  },
  {
    id: 8,
    name: "쿠키런: 킹덤",
    description: "Devsisters",
    image: "https://edge.ssalmuk.com/editorImage/31c1f862e4b14adb8498f40bdbb5c52b.jfif",
    genre: "캐쥬얼",
    codes: [
      {
        code: "COOKIEKINGDOM",
        issueDate: "2025-08-15",
        expireDate: "2025-11-15",
        event: "크리스탈 500개 + 쿠키 소환권",
      },
    ],
    discountItems: [
      { id: 1, name: "크리스탈 × 2500", description: "크리스탈 직접 충전", type: "UID", discount: 10, originalPrice: 27000 },
      { id: 2, name: "크리스탈 × 6500", description: "크리스탈 대량 충전", type: "UID", discount: 13, originalPrice: 65000 },
      { id: 3, name: "쿠키 소환권 10장", description: "레어 이상 쿠키 소환권", type: "PIN", discount: 12, originalPrice: 19000 },
      { id: 4, name: "쿠키 소환권 30장", description: "에픽 쿠키 소환 보장 번들", type: "PIN", discount: 15, originalPrice: 49000 },
      { id: 5, name: "왕국 건설 패키지", description: "건물 업그레이드 재료 대량 번들", type: "PIN", discount: 10, originalPrice: 35000 },
      { id: 6, name: "마법 사탕 패키지", description: "쿠키 레벨업 재료 번들", type: "PIN", discount: 8, originalPrice: 15000 },
      { id: 7, name: "시즌 패스", description: "이번 시즌 배틀패스 전체", type: "PIN", discount: 10, originalPrice: 14900 },
    ],
  },
  {
    id: 9,
    name: "블루 아카이브",
    description: "Nexon",
    image: "https://edge.ssalmuk.com/editorImage/86b0f36e3c9c4fbeb623414a29f955cb.jfif",
    genre: "RPG",
    codes: [
      {
        code: "BLUEARCHIVE25",
        issueDate: "2025-06-20",
        expireDate: "2025-09-30",
        event: "청휘석 1200개",
      },
    ],
    discountItems: [
      { id: 1, name: "청휘석 × 8000", description: "청휘석 직접 충전", type: "UID", discount: 15, originalPrice: 89000 },
      { id: 2, name: "청휘석 × 3000", description: "청휘석 소량 충전", type: "UID", discount: 12, originalPrice: 35000 },
      { id: 3, name: "선생님 번들팩", description: "청휘석 + 장비 강화 번들", type: "PIN", discount: 12, originalPrice: 49000 },
      { id: 4, name: "픽업 소환권 10장", description: "픽업 학생 소환권 번들", type: "PIN", discount: 18, originalPrice: 59000 },
      { id: 5, name: "장비 강화 패키지", description: "장비 강화 재료 + 청휘석 번들", type: "PIN", discount: 15, originalPrice: 39000 },
      { id: 6, name: "시즌 패스", description: "이번 시즌 배틀패스 전체 보상", type: "PIN", discount: 10, originalPrice: 19000 },
      { id: 7, name: "카페 꾸미기 패키지", description: "카페 인테리어 아이템 번들", type: "PIN", discount: 8, originalPrice: 25000 },
      { id: 8, name: "총력전 지원팩", description: "총력전 도전권 + 아이템 번들", type: "PIN", discount: 20, originalPrice: 45000 },
    ],
  },
  {
    id: 10,
    name: "원신",
    description: "miHoYo",
    image: "https://edge.ssalmuk.com/editorImage/c93c02b72a9b4a5780f4c66127ca262b.jpg",
    genre: "RPG",
    codes: [
      {
        code: "GENSHIN2025",
        issueDate: "2025-07-10",
        expireDate: "정보없음",
        event: "원석 60개 + 모라 50000",
      },
    ],
    discountItems: [
      { id: 1, name: "창천수지 × 6480", description: "프리미엄 가차 재화 직접 충전", type: "UID", discount: 15, originalPrice: 129000 },
      { id: 2, name: "창천수지 × 3280", description: "가차 재화 직접 충전", type: "UID", discount: 12, originalPrice: 69000 },
      { id: 3, name: "창천수지 × 1600", description: "가차 재화 소량 충전", type: "UID", discount: 10, originalPrice: 35000 },
      { id: 4, name: "모험가 번들팩", description: "레벨업 지원 + 원소석 번들", type: "PIN", discount: 10, originalPrice: 49000 },
      { id: 5, name: "신규 캐릭터 스타터팩", description: "신규 캐릭터 전용 무기 + 재료 번들", type: "PIN", discount: 18, originalPrice: 79000 },
      { id: 6, name: "원소 성유물 팩", description: "성유물 강화 재료 대량 번들", type: "PIN", discount: 13, originalPrice: 39000 },
      { id: 7, name: "탐험 지원팩", description: "체력 물약 + 이동속도 버프 번들", type: "PIN", discount: 8, originalPrice: 19000 },
      { id: 8, name: "시즌 패스 웰킨달", description: "월간 웰킨달의 축복 구독권", type: "PIN", discount: 20, originalPrice: 9900 },
    ],
    productInfo: {
      checkMethod: "내 구매내역 > 상품 정보 > 상품 코드 확인",
      registerSteps: [
        "원신 공식 충전 상점 접속",
        "- https://genshin.hoyoverse.com/",
        "상단 메뉴 내 [교환/REDEEM] 클릭",
        "원신 게임이 연동된 계정으로 로그인",
        "상품 코드(REDEEM CODE) 입력 후 교환 확인",
      ],
      note: "PIN 번호 형태의 디지털 상품권은 상품 특성상 발급(또는 노출) 이후에는 환불이 불가능합니다.",
    },
  },
];

export const genres = ["전체", "MMORPG", "RPG", "방치형", "캐쥬얼"];
